In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

In [2]:
import pandas as pd

In [25]:
# Define the chunk size
chunk_size = 500000  # Adjust this number based on your needs

# Path to your file in Google Drive
file_path = '/content/drive/My Drive/Phase 5/meta_Movies_and_TV.jsonl'

# Read the first chunk of the JSON data
meta_chunk = pd.read_json(file_path, lines=True, chunksize=chunk_size)

# Get the first chunk
df_meta = next(meta_chunk)

# save chunk to a CSV file
df_meta.to_csv('/content/drive/My Drive/Phase 5/meta_movies_500000.csv', index=False)

In [26]:
df_meta = pd.read_csv('/content/drive/My Drive/Phase 5/meta_movies_500000.csv')
df_meta.head(5)

<ipython-input-26-316ac7c2c17a>:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_meta = pd.read_csv('/content/drive/My Drive/Phase 5/meta_movies_500000.csv')

,main_category,title,subtitle,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,author
0,Prime Video,Glee,UnentitledUnentitled,4.7,2004.0,"['IMDb 6.8', '2013', '22 episodes', 'X-Ray', '...","['Entering its fourth season, this year the me...",22.39,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,"['Comedy', 'Drama', 'Arts, Entertainment, and ...","{'Content advisory': ['Violence', 'substance u...",B00ABWKL3I,NaN,NaN
1,Prime Video,One Perfect Wedding,NaN,3.0,6.0,"['IMDb 6.1', '1 h 27 min', '2021', 'ALL']",['With her book tour in two weeks and his expa...,NaN,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,"['Comedy', 'Drama', 'Romance']","{'Audio languages': ['English'], 'Subtitles': ...",B09WDLJ4HP,NaN,NaN
2,Movies & TV,How to Make Animatronic Characters - Organic M...,NaN,5.0,7.0,[],"['Product Description', 'In PART TWO of this i...",64.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],"Rick Lazzarini (Actor), Stan Winston Scho...","['Movies & TV', 'Genre for Featured Categories...",{'Package Dimensions': '7.52 x 5.31 x 0.71 inc...,B00AHN851G,NaN,NaN
3,Prime Video,Ode to Joy: Beethoven's Symphony No. 9,NaN,4.3,35.0,"['1 h 26 min', '2015', 'ALL']","[""This special Ode to Joy: Beethoven's Symphon...",5.99,[{'360w': 'https://m.media-amazon.com/images/G...,[],NaN,['Documentary'],"{'Audio languages': ['English'], 'Subtitles': ...",B01G9ILXXE,NaN,NaN
4,Prime Video,Ben 10: Alien Force (Classic),UnentitledUnentitled,4.7,360.0,"['IMDb 7.3', '2008', '13 episodes', '7+']",['Itâ€™s hero time again for Ben as he saves t...,24.49,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,"['Science Fiction', 'Comedy', 'Animation', 'Dr...","{'Audio languages': ['English'], 'Subtitles': ...",B009SIYXDA,NaN,NaN

In [27]:
# prompt: I want to filter by Prime Video from the column main_category

# Filter the DataFrame by 'main_category'
prime_video_df = df_meta[df_meta['main_category'] == 'Prime Video']

# Display the filtered DataFrame
prime_video_df.head(5)

,main_category,title,subtitle,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,author
0,Prime Video,Glee,UnentitledUnentitled,4.7,2004.0,"['IMDb 6.8', '2013', '22 episodes', 'X-Ray', '...","['Entering its fourth season, this year the me...",22.39,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,"['Comedy', 'Drama', 'Arts, Entertainment, and ...","{'Content advisory': ['Violence', 'substance u...",B00ABWKL3I,NaN,NaN
1,Prime Video,One Perfect Wedding,NaN,3.0,6.0,"['IMDb 6.1', '1 h 27 min', '2021', 'ALL']",['With her book tour in two weeks and his expa...,NaN,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,"['Comedy', 'Drama', 'Romance']","{'Audio languages': ['English'], 'Subtitles': ...",B09WDLJ4HP,NaN,NaN
3,Prime Video,Ode to Joy: Beethoven's Symphony No. 9,NaN,4.3,35.0,"['1 h 26 min', '2015', 'ALL']","[""This special Ode to Joy: Beethoven's Symphon...",5.99,[{'360w': 'https://m.media-amazon.com/images/G...,[],NaN,['Documentary'],"{'Audio languages': ['English'], 'Subtitles': ...",B01G9ILXXE,NaN,NaN
4,Prime Video,Ben 10: Alien Force (Classic),UnentitledUnentitled,4.7,360.0,"['IMDb 7.3', '2008', '13 episodes', '7+']",['Itâ€™s hero time again for Ben as he saves t...,24.49,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,"['Science Fiction', 'Comedy', 'Animation', 'Dr...","{'Audio languages': ['English'], 'Subtitles': ...",B009SIYXDA,NaN,NaN
6,Prime Video,Let Sleeping Corpses Lie,NaN,4.2,96.0,"['IMDb 6.8', '1 h 32 min', '1975', 'R']",['A cop chases two hippies suspected of a seri...,NaN,[{'360w': 'https://m.media-amazon.com/images/G...,[],NaN,"['Horror', 'Atmospheric', 'Intense']","{'Subtitles': ['None available'], 'Directors':...",B018RDV40G,NaN,NaN

In [ ]:
# prompt: drop columns: subtitle, features,images,store,author,,bought_together,details

# Drop specified columns
columns_to_drop = ['subtitle', 'features', 'images', 'store', 'author', 'bought_together', 'details','videos']
prime_video_df = prime_video_df.drop(columns=columns_to_drop, errors='ignore')

prime_video_df.head(5)

,main_category,title,average_rating,rating_number,description,price,categories,parent_asin
0,Prime Video,Glee,4.7,2004.0,"['Entering its fourth season, this year the me...",22.39,"['Comedy', 'Drama', 'Arts, Entertainment, and ...",B00ABWKL3I
1,Prime Video,One Perfect Wedding,3.0,6.0,['With her book tour in two weeks and his expa...,NaN,"['Comedy', 'Drama', 'Romance']",B09WDLJ4HP
3,Prime Video,Ode to Joy: Beethoven's Symphony No. 9,4.3,35.0,"[""This special Ode to Joy: Beethoven's Symphon...",5.99,['Documentary'],B01G9ILXXE
4,Prime Video,Ben 10: Alien Force (Classic),4.7,360.0,['Itâ€™s hero time again for Ben as he saves t...,24.49,"['Science Fiction', 'Comedy', 'Animation', 'Dr...",B009SIYXDA
6,Prime Video,Let Sleeping Corpses Lie,4.2,96.0,['A cop chases two hippies suspected of a seri...,NaN,"['Horror', 'Atmospheric', 'Intense']",B018RDV40G

In [29]:
prime_video_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 237347 entries, 0 to 499998
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   main_category   237347 non-null  object
 1   title           35130 non-null   object
 2   average_rating  237169 non-null  float64
 3   rating_number   237169 non-null  float64
 4   description     35130 non-null   object
 5   price           21676 non-null   object
 6   categories      35130 non-null   object
 7   parent_asin     237347 non-null  object
dtypes: float64(2), object(6)
memory usage: 16.3+ MB

In [ ]:
# prompt: the category column is an object that looks like ['Comedy', 'Drama', 'Romance']	I want to pick the first word in that object. How can I achieve this?

prime_video_df['categories'] = prime_video_df['categories'].astype(str).str.split(',').str[0].str.strip()
prime_video_df.head()

,main_category,title,average_rating,rating_number,description,price,categories,parent_asin
0,Prime Video,Glee,4.7,2004.0,"['Entering its fourth season, this year the me...",22.39,['Comedy',B00ABWKL3I
1,Prime Video,One Perfect Wedding,3.0,6.0,['With her book tour in two weeks and his expa...,NaN,['Comedy',B09WDLJ4HP
3,Prime Video,Ode to Joy: Beethoven's Symphony No. 9,4.3,35.0,"[""This special Ode to Joy: Beethoven's Symphon...",5.99,['Documentary'],B01G9ILXXE
4,Prime Video,Ben 10: Alien Force (Classic),4.7,360.0,['Itâ€™s hero time again for Ben as he saves t...,24.49,['Science Fiction',B009SIYXDA
6,Prime Video,Let Sleeping Corpses Lie,4.2,96.0,['A cop chases two hippies suspected of a seri...,NaN,['Horror',B018RDV40G

In [ ]:
# prompt: How do I remove the characters [''] e.g ['Documentary']  ['Comedy'

prime_video_df['categories'] = prime_video_df['categories'].astype(str).str.replace(r"\['|'|\]", '', regex=True)
prime_video_df.head()

,main_category,title,average_rating,rating_number,description,price,categories,parent_asin
0,Prime Video,Glee,4.7,2004.0,"['Entering its fourth season, this year the me...",22.39,Comedy,B00ABWKL3I
1,Prime Video,One Perfect Wedding,3.0,6.0,['With her book tour in two weeks and his expa...,NaN,Comedy,B09WDLJ4HP
3,Prime Video,Ode to Joy: Beethoven's Symphony No. 9,4.3,35.0,"[""This special Ode to Joy: Beethoven's Symphon...",5.99,Documentary,B01G9ILXXE
4,Prime Video,Ben 10: Alien Force (Classic),4.7,360.0,['Itâ€™s hero time again for Ben as he saves t...,24.49,Science Fiction,B009SIYXDA
6,Prime Video,Let Sleeping Corpses Lie,4.2,96.0,['A cop chases two hippies suspected of a seri...,NaN,Horror,B018RDV40G

In [32]:
prime_video_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 237347 entries, 0 to 499998
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   main_category   237347 non-null  object
 1   title           35130 non-null   object
 2   average_rating  237169 non-null  float64
 3   rating_number   237169 non-null  float64
 4   description     35130 non-null   object
 5   price           21676 non-null   object
 6   categories      237347 non-null  object
 7   parent_asin     237347 non-null  object
dtypes: float64(2), object(6)
memory usage: 16.3+ MB

In [16]:
# Define the chunk size
chunk_size = 500000  # Adjust this number based on your needs

# Path to your file in Google Drive
file_path = '/content/drive/My Drive/Phase 5/Movies_and_TV.jsonl'

# Read the first chunk of the JSON data
reviews_chunk = pd.read_json(file_path, lines=True, chunksize=chunk_size)

# Get the first chunk
df_meta = next(reviews_chunk)

# save chunk to a CSV file
df_meta.to_csv('/content/drive/My Drive/Phase 5/reviews_movies_500000.csv', index=False)

In [33]:
reviews_df = pd.read_csv('/content/drive/My Drive/Phase 5/reviews_movies_500000.csv')
reviews_df.head(5)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5,Five Stars,"Amazon, please buy the show! I'm hooked!",[],B013488XFS,B013488XFS,AGGZ357AO26RQZVRLGU4D4N52DZQ,2015-08-24 03:07:17.000,0,True
1,5,Five Stars,My Kiddos LOVE this show!!,[],B00CB6VTDS,B00CB6VTDS,AGKASBHYZPGTEPO6LWZPVJWB2BVA,2016-04-19 21:16:50.000,0,True
2,3,Some decent moments...but...,Annabella Sciorra did her character justice wi...,[],B096Z8Z3R6,B096Z8Z3R6,AG2L7H23R5LLKDKLBEF2Q3L2MVDA,2022-03-03 01:43:54.582,0,True
3,4,"Decent Depiction of Lower-Functioning Autism, ...",...there should be more of a range of characte...,[],B09M14D9FZ,B09M14D9FZ,AG2L7H23R5LLKDKLBEF2Q3L2MVDA,2022-02-27 04:56:01.864,1,False
4,5,What Love Is...,"...isn't always how you expect it to be, but w...",[],B001H1SVZC,B001H1SVZC,AG2L7H23R5LLKDKLBEF2Q3L2MVDA,2020-05-28 04:13:47.074,0,True

In [34]:
# Drop specified columns
columns_to_drop = ['images','user_id','helpful_vote']
reviews_df = reviews_df.drop(columns=columns_to_drop, errors='ignore')

reviews_df.head(5)

,rating,title,text,asin,parent_asin,timestamp,verified_purchase
0,5,Five Stars,"Amazon, please buy the show! I'm hooked!",B013488XFS,B013488XFS,2015-08-24 03:07:17.000,True
1,5,Five Stars,My Kiddos LOVE this show!!,B00CB6VTDS,B00CB6VTDS,2016-04-19 21:16:50.000,True
2,3,Some decent moments...but...,Annabella Sciorra did her character justice wi...,B096Z8Z3R6,B096Z8Z3R6,2022-03-03 01:43:54.582,True
3,4,"Decent Depiction of Lower-Functioning Autism, ...",...there should be more of a range of characte...,B09M14D9FZ,B09M14D9FZ,2022-02-27 04:56:01.864,False
4,5,What Love Is...,"...isn't always how you expect it to be, but w...",B001H1SVZC,B001H1SVZC,2020-05-28 04:13:47.074,True

In [ ]:
# prompt: I want to merge reviews_df with prime_video_df using the parent_asin column

# Merge the two DataFrames
merged_df = pd.merge(reviews_df, prime_video_df, on='parent_asin', how='inner')

# Display the merged DataFrame
merged_df.head()

,rating,title_x,text,asin,parent_asin,timestamp,verified_purchase,main_category,title_y,average_rating,rating_number,description,price,categories
0,5,Five Stars,"Amazon, please buy the show! I'm hooked!",B013488XFS,B013488XFS,2015-08-24 03:07:17.000,True,Prime Video,Sneaky Pete,4.6,56658.0,['A\xa0con man (Giovanni Ribisi) on the run fr...,NaN,Suspense
1,5,Five Stars,My Kiddos LOVE this show!!,B00CB6VTDS,B00CB6VTDS,2016-04-19 21:16:50.000,True,Prime Video,Creative Galaxy,4.8,6403.0,['Follow the adventures of Arty and his sideki...,NaN,Kids
2,5,What Love Is...,"...isn't always how you expect it to be, but w...",B001H1SVZC,B001H1SVZC,2020-05-28 04:13:47.074,True,Prime Video,NaN,4.5,389.0,NaN,NaN,nan
3,5,QUIRKY TURNS TO HEARTSTRINGS,As you learn about the very unique characters ...,B06WVW16WY,B06WVW16WY,2020-04-16 01:15:47.540,True,Prime Video,NaN,4.8,1966.0,NaN,NaN,nan
4,5,Way better than the harsh reviews.,Our family loved the film. We have kids and th...,B07RXM26FG,B07RXM26FG,2019-09-29 05:17:12.700,True,Prime Video,NaN,4.5,57962.0,NaN,NaN,nan

In [36]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233610 entries, 0 to 233609
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   rating             233610 non-null  int64
 1   title_x            233586 non-null  object
 2   text               233579 non-null  object
 3   asin               233610 non-null  object
 4   parent_asin        233610 non-null  object
 5   timestamp          233610 non-null  object
 6   verified_purchase  233610 non-null  bool
 7   main_category      233610 non-null  object
 8   title_y            33800 non-null   object
 9   average_rating     233607 non-null  float64
 10  rating_number      233607 non-null  float64
 11  description        33800 non-null   object
 12  price              24165 non-null   object
 13  categories         233610 non-null  object
dtypes: bool(1), float64(2), int64(1), object(10)
memory usage: 23.4+ MB

In [37]:
merged_df['categories'].value_counts()

categories
nan                          199810
Suspense                       7518
Comedy                         7508
Drama                          7075
Science Fiction                3945
Documentary                    1604
Fantasy                         802
Action                          785
Unscripted                      753
Historical                      567
Kids                            474
Animation                       411
Horror                          379
Adventure                       325
Special Interest                322
International                   218
Young Adult Audience            203
[                               171
Romance                         141
Western                         132
Sports                           96
Arts                             86
Faith and Spirituality           64
LGBTQ                            54
Music Videos and Concerts        40
Military and War                 38
Arthouse                         31
Fitness                          30
Anime                            20
Talk Show and Variety             8
Name: count, dtype: int64